# Railway configuration for D&D DM Chatbot
# This file configures the main backend service
# Frontend and Ollama should be deployed as separate services

[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm install && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }